SWAP_SPEED = 4;
FALL_ACCELERATION = 0.2;
FALL_SPEED = 5;
JUMP_SPEED = 7;
SHOT_SPEED = 3.5;

POLE_COUNT = 4;
POLE_DISTANCE = 240;
POLE_DISTANCE_FROM_EDGE = 200;
SCREEN_HEIGHT = 800;

STARTING_BLOCKS = 6;
BLOCK_HEIGHT = 50;

DEBUG_MODE = false;

GROUND_LEVEL = 720; // canvas pixels

VICTORY_BLOCKS = 12;

MAX_ACTIVE_PROJECTILES_PER_PLAYER = 1;

BLOCK_BOTH_DIRECTIONS = true;

HOLD_TO_SWAP = true;

STARTING_TYPES = [
    'LBEJRBRJEB',
    'BREJBLBJEB'
];

APPEAR_TYPES = [
    'SBJE',
    'BSJE'
];

AVOID_CREATING_OVERREPRESENTED_BLOCKS = true;


CAN_AIM_EAGLES = false;

MATCH_THREE_EMPTY = true;

SHIELD_HITPOINTS = 3; // Set to -1 for invulnerable

FIRST_BLOCK_APPEAR = 12; // seconds
BLOCK_APPEAR_INTERVAL = 6; // seconds
BLOCK_APPEAR_INTERVAL_REDUCE = 1; // seconds, each block appearing reduces the interval with this value
BLOCK_APPEAR_INTERVAL_MIN = 4; // seconds

START_COUNTDOWN_DURATION = 3; // seconds
MIN_VICTORY_TIME = 1; // seconds

SOUND_ON = true;

TINTING_AMOUNT = 0; // from 0 to 1

CURSOR_WIDTH = 52;

CURSOR_HEIGHT = 52;

BEAVER_SPAWN_BLOCKS = 4;

MAX_PARTICLES = 100;
PARTICLE_SIZE = 6;
EMISSION_RATE = 30;
OBJECT_SIZE = 5;