SWAP_SPEED = 4;
FALL_ACCELERATION = 0.2;
FALL_SPEED = 5;
JUMP_SPEED = 7;
SHOT_SPEED = 3;

POLE_COUNT = 2;
POLE_DISTANCE = 350;

STARTING_BLOCKS = 10;
BLOCK_HEIGHT = 50;

MAX_ACTIVE_PROJECTILES_PER_PLAYER = 1;

BLOCK_BOTH_DIRECTIONS = true;

STARTING_TYPES = [
    'LBEJBBRJEB',
    'BREJBLBJEB',
    'LBEJBBRJEB',
    'BREJBLBJEB'
];