SWAP_SPEED = 4;
FALL_ACCELERATION = 0.2;
FALL_SPEED = 5;
JUMP_SPEED = 7;
SHOT_SPEED = 3;

POLE_COUNT = 4;
POLE_DISTANCE = 240;
SCREEN_WIDTH = 1100;

STARTING_BLOCKS = 8;
BLOCK_HEIGHT = 50;


DEBUG_MODE = false;

GROUND_LEVEL = 650; // canvas pixels

VICTORY_BLOCKS = 12;

MAX_ACTIVE_PROJECTILES_PER_PLAYER = 1;

BLOCK_BOTH_DIRECTIONS = true;

HOLD_TO_SWAP = true;

STARTING_TYPES = [
    'LBEJBBRJEB',
    'BREJBLBJEB'
];

APPEAR_TYPES = [
    'SBJ',
    'BSJ'
];

AVOID_CREATING_OVERREPRESENTED_BLOCKS = true;

CAN_AIM_EAGLES = true;

FIRST_BLOCK_APPEAR = 20; // seconds
BLOCK_APPEAR_INTERVAL = 15; // seconds
BLOCK_APPEAR_INTERVAL_REDUCE = 1; // seconds, each block appearing reduces the interval with this value
BLOCK_APPEAR_INTERVAL_MIN = 5; // seconds

START_COUNTDOWN_DURATION = 3; // seconds

SOUND_ON = false;

TINTING_AMOUNT = 0; // from 0 to 1

CURSOR_WIDTH = 52;
CURSOR_HEIGHT = 52;